---
name: Rafael
surname: França
position: "Market risk analyst"
phone: +55 11 98757 1851
email: "rafael.defranca@outlook.com"
github: rmfranca
linkedin: francar
aboutme: "Experienced risk professional with a background in finance & consulting in the Brazilian market."
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(here)
```

```{r functions}
readExcelSheets <- function(filename){
  # read all sheets in .xlsx 
  all <- readxl::excel_sheets(filename)
  
  # import each sheet into a list using readxl::read_excel
  list <- lapply(all, function(x) readxl::read_excel(filename, sheet = x))
  
  # save sheet name for each sheet (list)
  names(list) <- all
  
  # breaks up list and creates a dataframe for each sheet with df names matching sheet names
  list2env(list, envir = .GlobalEnv)
}
```

```{r load-data, message=F, results='hide'}
filename <- here::here("cvdata.xlsx")
readExcelSheets(filename)
```

<!-- # Some stuff about me -->

<!--  * I poisoned myself doing research. -->
<!--  * I was the first woman to win a Nobel prize -->
<!--  * I was the first person and only woman to win a Nobel prize in two different sciences. -->

# Education

```{r}
# library(tibble)
# tribble(
#   ~ Degree, ~ Year, ~ Institution, ~ Where,
#   "Informal studies", "1889-91", "Flying University", "Warsaw, Poland",
#   "Master of Physics", "1893", "Sorbonne Université", "Paris, France",
#   "Master of Mathematics", "1894", "Sorbonne Université", "Paris, France"
# ) %>% 
#    detailed_entries(Degree, Year, Institution, Where)
education %>% 
  detailed_entries(what = degree,
                   when = year,
                   with = institution,
                   where = where,
                   why = details)
```

# Industry experience
```{r}
industry %>% 
  detailed_entries(what = role,
                   when = dates,
                   with = institution,
                   where = where,
                   why = details)
```

# Skills
```{r}
skills %>% 
    detailed_entries(what = what,
                   with = with)
```

# Qualifications
```{r}
qualifications %>% 
  brief_entries(what = institution,
                when = dates)
```

```{r}
# library(dplyr)
# knitr::write_bib(c("vitae", "tibble"), "packages.bib")
# 
# bibliography_entries("packages.bib") %>%
#   arrange(desc(author$family), issued)
# 
#bibliography_entries(here("kate_dibiasky_vitae_cv", "papers.bib")) 
```

<!-- ## Another way to display publications is using R Markdown. You can also use latex commands throughout the document: -->

<!-- \setlength{\leftskip}{0cm} -->
<!-- **2022** -->

<!-- \setlength{\leftskip}{1cm} -->
<!-- [**Dibiasky, K.** and Mindy, R. (2022). *Discovery of a novel comet, Comet Dibiasky, heading towards Earth.* Science.](https://media.giphy.com/media/q9CS6tp1oM45pmj19U/giphy.gif) -->